;;; graph-fa2-baseline.el --- Baseline performance functions for ForceAtlas2 -*- lexical-binding: t; no-byte-compile: t;-*-

(require 'graph-fa2)

(defun baseline-sync-nodes (ctx total-nodes)
  "Synchronise tracking arrays with internal node structs in CTX for TOTAL-NODES."
  (let ((nodes (graph-fa2-ctx-nodes ctx))
        (pos-x (graph-fa2-ctx-pos-x ctx))
        (pos-y (graph-fa2-ctx-pos-y ctx))
        (pos-z (graph-fa2-ctx-pos-z ctx))
        (vel-x (graph-fa2-ctx-vel-x ctx))
        (vel-y (graph-fa2-ctx-vel-y ctx))
        (vel-z (graph-fa2-ctx-vel-z ctx)))
    (dotimes (i total-nodes)
      (let ((n (aref nodes i)))
        (fa2-set-x n (aref pos-x i))
        (fa2-set-y n (aref pos-y i))
        (fa2-set-z n (aref pos-z i))
        (fa2-set-dx n (aref vel-x i))
        (fa2-set-dy n (aref vel-y i))
        (fa2-set-dz n (aref vel-z i))))))

(defun baseline-render-svg (ctx len)
  "Render the current layout integer arrays to an SVG string using a two-dimensional projection.

Parameters:
CTX: The simulation context.
LEN: The active node count."
  (when-let* ((nodes (graph-fa2-ctx-nodes ctx))
              (edges (graph-fa2-ctx-edges ctx))
              (pos-x (graph-fa2-ctx-pos-x ctx))
              (pos-y (graph-fa2-ctx-pos-y ctx))
              (pos-z (graph-fa2-ctx-pos-z ctx)))
    (let ((gc-cons-threshold most-positive-fixnum))
      (with-current-buffer (graph-fa2-ctx-bg-buffer ctx)
        (dolist (edge edges)
          (when-let* (((< (car edge) len))
                      ((< (cdr edge) len))
                      (u-idx (car edge))
                      (v-idx (cdr edge))
                      (u-coords (graph-fa2-normalise-coords (aref pos-x u-idx) (aref pos-y u-idx) (aref pos-z u-idx)))
                      (v-coords (graph-fa2-normalise-coords (aref pos-x v-idx) (aref pos-y v-idx) (aref pos-z v-idx)))
                      (ux (format "%.3f" (car u-coords)))
                      (uy (format "%.3f" (cadr u-coords)))
                      (vx (format "%.3f" (car v-coords)))
                      (vy (format "%.3f" (cadr v-coords))))
            (insert "  <line x1=\"" ux "\" y1=\"" uy "\" x2=\"" vx "\" y2=\"" vy "\" stroke=\"" graph-fa2-edge-colour "\" stroke-width=\"" (number-to-string graph-fa2-edge-width) "\" />\n")))
        (dotimes (i len)
          (when-let* ((n (aref nodes i))
                      (coords (graph-fa2-normalise-coords (aref pos-x i) (aref pos-y i) (aref pos-z i)))
                      (nx-float (car coords))
                      (ny-float (cadr coords))
                      (nz-float (caddr coords))
                      (nx (format "%.3f" nx-float))
                      (ny (format "%.3f" ny-float))
                      (nz (format "%.3f" nz-float))
                      (id (fa2-id n))
                      (label (fa2-label n))
                      (radius (fa2-radius n))
                      (colour (fa2-colour n))
                      (name-escaped (graph-fa2--escape-xml label))
                      (lines (graph-fa2--wrap-text name-escaped graph-fa2-label-wrap-chars))
                      (line-height (max 1 (round (* graph-fa2-label-font-size 1.2))))
                      (start-y (- ny-float graph-fa2-label-offset-y (* (1- (length lines)) (/ line-height 2)))))
            (insert "  <circle cx=\"" nx "\" cy=\"" ny "\" r=\"" (format "%.3f" radius) "\" fill=\"" colour "\" data-name=\"" (graph-fa2--escape-xml id) "\" data-depth=\"" nz "\" />\n")
            (insert "  <text fill=\"" graph-fa2-label-colour
                    "\" font-size=\"" (number-to-string graph-fa2-label-font-size) "\""
                    (if graph-fa2-label-font-family
                        (concat " font-family=\"" graph-fa2-label-font-family "\"") "")
                    (if graph-fa2-label-font-weight
                        (concat " font-weight=\"" graph-fa2-label-font-weight "\"") "")
                    " text-anchor=\"middle\">\n")
            (let ((curr-y start-y))
              (dolist (line lines)
                (insert "    <tspan x=\"" nx "\" y=\"" (format "%.3f" curr-y) "\">" line "</tspan>\n")
                (cl-incf curr-y line-height)))
            (insert "  </text>\n")))
        (insert "<FRAME_SPLIT>\n")))))

(defun baseline-2d-compute-repulsion (ctx len a)
  "Compute two-dimensional repulsion between all active node pairs in CTX for LEN nodes with scaling A."
  (let* ((pos-x (graph-fa2-ctx-pos-x ctx))
         (pos-y (graph-fa2-ctx-pos-y ctx))
         (rep-x (graph-fa2-ctx-rep-x ctx))
         (rep-y (graph-fa2-ctx-rep-y ctx))
         (mass-matrix (graph-fa2-ctx-mass-matrix ctx))
         (total-nodes (length (graph-fa2-ctx-nodes ctx))))
    (fillarray rep-x 0)
    (fillarray rep-y 0)
    (let ((gc-cons-threshold most-positive-fixnum))
      (dotimes (i len)
        (let ((nix (aref pos-x i))
              (niy (aref pos-y i))
              (i-offset (* i total-nodes)))
          (cl-loop for j from (1+ i) below len do
                   (let* ((dx (- nix (aref pos-x j)))
                          (abs-dx (if (< dx 0) (- dx) dx)))
                     (when (< abs-dx graph-fa2-repulsion-x-y-threshold)
                       (let* ((dy (- niy (aref pos-y j)))
                              (abs-dy (if (< dy 0) (- dy) dy)))
                         (when (< abs-dy graph-fa2-repulsion-x-y-threshold)
                           (let* ((max-d (if (> abs-dx abs-dy) abs-dx abs-dy))
                                  (min-d (if (> abs-dx abs-dy) abs-dy abs-dx))
                                  (dist (if (= max-d 0) 1 (+ max-d (ash (truncate min-d) -1))))
                                  (dist-sq (+ (* dx dx) (* dy dy)))
                                  (dist-sq (if (< dist-sq graph-fa2-repulsion-threshold) graph-fa2-repulsion-threshold dist-sq)))
                             (when (< dist-sq graph-fa2-repulsion-max-dist-sq)
                               (let* ((mass-mult (truncate (aref mass-matrix (+ i-offset j))))
                                      (num (ash (truncate (* a mass-mult)) 16))
                                      (den (* dist dist-sq))
                                      (fdx (/ (* dx num) den))
                                      (fdy (/ (* dy num) den)))
                                 (aset rep-x i (+ (aref rep-x i) fdx))
                                 (aset rep-y i (+ (aref rep-y i) fdy))
                                 (aset rep-x j (- (aref rep-x j) fdx))
                                 (aset rep-y j (- (aref rep-y j) fdy)))))))))))))))

(defun baseline-2d-apply-repulsion (ctx len)
  "Add accumulated two-dimensional repulsion forces in CTX for LEN nodes."
  (let ((vel-x (graph-fa2-ctx-vel-x ctx))
        (vel-y (graph-fa2-ctx-vel-y ctx))
        (rep-x (graph-fa2-ctx-rep-x ctx))
        (rep-y (graph-fa2-ctx-rep-y ctx)))
    (dotimes (i len)
      (aset vel-x i (+ (aref vel-x i) (aref rep-x i)))
      (aset vel-y i (+ (aref vel-y i) (aref rep-y i))))))

(defun baseline-2d-apply-attraction (ctx len a)
  "Calculate and apply edge-based two-dimensional attraction forces in CTX for LEN nodes."
  (let ((pos-x (graph-fa2-ctx-pos-x ctx))
        (pos-y (graph-fa2-ctx-pos-y ctx))
        (vel-x (graph-fa2-ctx-vel-x ctx))
        (vel-y (graph-fa2-ctx-vel-y ctx))
        (edges (graph-fa2-ctx-edges ctx)))
    (dolist (edge edges)
      (when (and (< (car edge) len) (< (cdr edge) len))
        (let* ((u (car edge))
               (v (cdr edge))
               (dx (- (aref pos-x u) (aref pos-x v)))
               (dy (- (aref pos-y u) (aref pos-y v)))
               (abs-dx (if (< dx 0) (- dx) dx))
               (abs-dy (if (< dy 0) (- dy) dy))
               (max-d (if (> abs-dx abs-dy) abs-dx abs-dy))
               (min-d (if (> abs-dx abs-dy) abs-dy abs-dx))
               (dist (if (= max-d 0) 1 (+ max-d (ash (truncate min-d) -1))))
               (dist-diff (- dist graph-fa2-attraction-threshold))
               (num (* a dist-diff))
               (den (ash (truncate dist) 16))
               (fdx (/ (* dx num) den))
               (fdy (/ (* dy num) den)))
          (aset vel-x u (- (aref vel-x u) fdx))
          (aset vel-y u (- (aref vel-y u) fdy))
          (aset vel-x v (+ (aref vel-x v) fdx))
          (aset vel-y v (+ (aref vel-y v) fdy)))))))

(defun baseline-2d-integrate-and-cull (ctx len a)
  "Process gravity, enforce speed limits, integrate positions, and cull nodes in 2D."
  (let ((pos-x (graph-fa2-ctx-pos-x ctx))
        (pos-y (graph-fa2-ctx-pos-y ctx))
        (vel-x (graph-fa2-ctx-vel-x ctx))
        (vel-y (graph-fa2-ctx-vel-y ctx))
        (nodes (graph-fa2-ctx-nodes ctx)))
    (dotimes (i len)
      (let* ((nx (aref pos-x i))
             (ny (aref pos-y i))
             (abs-nx (if (< nx 0) (- nx) nx))
             (abs-ny (if (< ny 0) (- ny) ny))
             (max-n (if (> abs-nx abs-ny) abs-nx abs-ny))
             (min-n (if (> abs-nx abs-ny) abs-ny abs-nx))
             (dist (if (= max-n 0) 1 (+ max-n (ash (truncate min-n) -1))))
             (mass (truncate (fa2-mass (aref nodes i))))
             (num (* a mass))
             (den (ash (truncate dist) 8))
             (fdx (/ (* nx num) den))
             (fdy (/ (* ny num) den)))
        (aset vel-x i (- (aref vel-x i) fdx))
        (aset vel-y i (- (aref vel-y i) fdy))
        (let* ((vx (aref vel-x i))
               (vy (aref vel-y i))
               (abs-vx (if (< vx 0) (- vx) vx))
               (abs-vy (if (< vy 0) (- vy) vy))
               (max-v (if (> abs-vx abs-vy) abs-vx abs-vy))
               (min-v (if (> abs-vx abs-vy) abs-vy abs-vx))
               (speed (if (= max-v 0) 1 (+ max-v (ash (truncate min-v) -1)))))
          (when (> speed 25)
            (let ((v-max graph-fa2-speed-limit-threshold))
              (aset vel-x i (/ (* (truncate vx) v-max) (+ speed v-max)))
              (aset vel-y i (/ (* (truncate vy) v-max) (+ speed v-max))))))
        (aset pos-x i (+ nx (ash (truncate (aref vel-x i)) -4)))
        (aset pos-y i (+ ny (ash (truncate (aref vel-y i)) -4)))
        (let* ((horizon graph-fa2-horizon-threshold)
               (horizon-start graph-fa2-horizon-start-threshold)
               (new-nx (aref pos-x i))
               (new-ny (aref pos-y i))
               (abs-new-nx (if (< new-nx 0) (- new-nx) new-nx))
               (abs-new-ny (if (< new-ny 0) (- new-ny) new-ny))
               (max-new (if (> abs-new-nx abs-new-ny) abs-new-nx abs-new-ny))
               (min-new (if (> abs-new-nx abs-new-ny) abs-new-ny abs-new-nx))
               (new-dist (if (= max-new 0) 1 (+ max-new (ash (truncate min-new) -1)))))
          (when (> new-dist horizon)
            (let ((clamp-scale (/ (ash horizon 16) new-dist)))
              (aset pos-x i (ash (truncate (* new-nx clamp-scale)) -16))
              (aset pos-y i (ash (truncate (* new-ny clamp-scale)) -16))
              (setq new-dist horizon)))
          (cond
           ((>= new-dist horizon)
            (aset vel-x i 0)
            (aset vel-y i 0))
           ((> new-dist horizon-start)
            (aset vel-x i (- (aref vel-x i) (ash (truncate (aref vel-x i)) -2)))
            (aset vel-y i (- (aref vel-y i) (ash (truncate (aref vel-y i)) -2))))
           (t
            (aset vel-x i (- (aref vel-x i) (ash (truncate (aref vel-x i)) -6)))
            (aset vel-y i (- (aref vel-y i) (ash (truncate (aref vel-y i)) -6))))))))))

(defun baseline-2d-physics-tick (ctx max-frames)
  "Calculate baseline ForceAtlas2 2D physics tick using arrays in CTX and limit MAX-FRAMES."
  (let* ((nodes (graph-fa2-ctx-nodes ctx))
         (total-nodes (length nodes)))
    (if (= total-nodes 0)
        (graph-fa2--render-empty ctx)
      (let* ((bg-frame (graph-fa2-ctx-bg-frame ctx))
             (len (if (< bg-frame 100)
                      (max 1 (truncate (* total-nodes (/ (float (1+ bg-frame)) 100.0))))
                    total-nodes))
             (a (max 2 (truncate (* 256.0 (- 1.0 (/ (float bg-frame) max-frames)))))))
        (baseline-2d-compute-repulsion ctx len a)
        (let ((gc-cons-threshold most-positive-fixnum))
          (dotimes (_ graph-fa2-substeps)
            (baseline-2d-apply-repulsion ctx len)
            (baseline-2d-apply-attraction ctx len a)
            (baseline-2d-integrate-and-cull ctx len a)))
        (baseline-sync-nodes ctx total-nodes)
        (baseline-render-svg ctx len)))))

(defun baseline-compute-repulsion-3d (ctx len a)
  "Compute 3D repulsion between active node pairs in CTX for LEN nodes."
  (let* ((pos-x (graph-fa2-ctx-pos-x ctx))
         (pos-y (graph-fa2-ctx-pos-y ctx))
         (pos-z (graph-fa2-ctx-pos-z ctx))
         (rep-x (graph-fa2-ctx-rep-x ctx))
         (rep-y (graph-fa2-ctx-rep-y ctx))
         (rep-z (graph-fa2-ctx-rep-z ctx))
         (mass-matrix (graph-fa2-ctx-mass-matrix ctx))
         (total-nodes (length (graph-fa2-ctx-nodes ctx))))
    (fillarray rep-x 0)
    (fillarray rep-y 0)
    (fillarray rep-z 0)
    (let ((gc-cons-threshold most-positive-fixnum))
      (dotimes (i len)
        (let ((nix (aref pos-x i))
              (niy (aref pos-y i))
              (niz (aref pos-z i))
              (i-offset (* i total-nodes)))
          (cl-loop for j from (1+ i) below len do
                   (when-let* ((dx (- nix (aref pos-x j)))
                               (dy (- niy (aref pos-y j)))
                               (dz (- niz (aref pos-z j)))
                               (dist (max 16 (graph-fa2--dist-3d dx dy dz)))
                               (raw-dist-sq (+ (* dx dx) (* dy dy) (* dz dz)))
                               (dist-sq (max 256 (if (< raw-dist-sq graph-fa2-repulsion-threshold) graph-fa2-repulsion-threshold raw-dist-sq)))
                               ((< dist-sq graph-fa2-repulsion-max-dist-sq))
                               (mass-mult (truncate (aref mass-matrix (+ i-offset j))))
                               (num (ash (truncate (* a mass-mult)) 16))
                               (den (max 256 (* dist dist-sq)))
                               (fdx (/ (* dx num) den))
                               (fdy (/ (* dy num) den))
                               (fdz (/ (* dz num) den)))
                     (aset rep-x i (+ (aref rep-x i) fdx))
                     (aset rep-y i (+ (aref rep-y i) fdy))
                     (aset rep-z i (+ (aref rep-z i) fdz))
                     (aset rep-x j (- (aref rep-x j) fdx))
                     (aset rep-y j (- (aref rep-y j) fdy))
                     (aset rep-z j (- (aref rep-z j) fdz)))))))))

(defun baseline-apply-repulsion-3d (ctx len)
  "Add accumulated 3D repulsion forces in CTX for LEN nodes."
  (let ((vel-x (graph-fa2-ctx-vel-x ctx))
        (vel-y (graph-fa2-ctx-vel-y ctx))
        (vel-z (graph-fa2-ctx-vel-z ctx))
        (rep-x (graph-fa2-ctx-rep-x ctx))
        (rep-y (graph-fa2-ctx-rep-y ctx))
        (rep-z (graph-fa2-ctx-rep-z ctx)))
    (dotimes (i len)
      (aset vel-x i (+ (aref vel-x i) (aref rep-x i)))
      (aset vel-y i (+ (aref vel-y i) (aref rep-y i)))
      (aset vel-z i (+ (aref vel-z i) (aref rep-z i))))))

(defun baseline-apply-attraction-3d (ctx len a)
  "Calculate and apply edge-based 3D attraction forces in CTX for LEN nodes."
  (let ((pos-x (graph-fa2-ctx-pos-x ctx))
        (pos-y (graph-fa2-ctx-pos-y ctx))
        (pos-z (graph-fa2-ctx-pos-z ctx))
        (vel-x (graph-fa2-ctx-vel-x ctx))
        (vel-y (graph-fa2-ctx-vel-y ctx))
        (vel-z (graph-fa2-ctx-vel-z ctx))
        (edges (graph-fa2-ctx-edges ctx)))
    (dolist (edge edges)
      (when (and (< (car edge) len) (< (cdr edge) len))
        (let* ((u (car edge))
               (v (cdr edge))
               (dx (- (aref pos-x u) (aref pos-x v)))
               (dy (- (aref pos-y u) (aref pos-y v)))
               (dz (- (aref pos-z u) (aref pos-z v)))
               (dist (graph-fa2--dist-3d dx dy dz))
               (dist-diff (- dist graph-fa2-attraction-threshold))
               (num (* a dist-diff))
               (den (ash dist 16))
               (fdx (/ (* dx num) den))
               (fdy (/ (* dy num) den))
               (fdz (/ (* dz num) den)))
          (aset vel-x u (- (aref vel-x u) fdx))
          (aset vel-y u (- (aref vel-y u) fdy))
          (aset vel-z u (- (aref vel-z u) fdz))
          (aset vel-x v (+ (aref vel-x v) fdx))
          (aset vel-y v (+ (aref vel-y v) fdy))
          (aset vel-z v (+ (aref vel-z v) fdz)))))))

(defun baseline-integrate-and-cull-3d (ctx len a progress-fp)
  "Process gravity, enforce speed limits, integrate positions, and manage spherical boundaries in 3D."
  (let ((pos-x (graph-fa2-ctx-pos-x ctx))
        (pos-y (graph-fa2-ctx-pos-y ctx))
        (pos-z (graph-fa2-ctx-pos-z ctx))
        (vel-x (graph-fa2-ctx-vel-x ctx))
        (vel-y (graph-fa2-ctx-vel-y ctx))
        (vel-z (graph-fa2-ctx-vel-z ctx))
        (nodes (graph-fa2-ctx-nodes ctx)))
    (dotimes (i len)
      (let* ((nx (aref pos-x i))
             (ny (aref pos-y i))
             (nz (aref pos-z i))
             (dist (max 1 (graph-fa2--dist-3d nx ny nz)))
             (mass (truncate (fa2-mass (aref nodes i))))
             (num (* a mass))
             (den (max 1 (ash dist 8)))
             (fdx (/ (* nx num) den))
             (fdy (/ (* ny num) den))
             (fdz (/ (* nz num) den)))
        (aset vel-x i (- (aref vel-x i) fdx))
        (aset vel-y i (- (aref vel-y i) fdy))
        (aset vel-z i (- (aref vel-z i) fdz))
        (let* ((vx (graph-fa2-clamp (aref vel-x i) 131072))
               (vy (graph-fa2-clamp (aref vel-y i) 131072))
               (vz (graph-fa2-clamp (aref vel-z i) 131072))
               (speed (graph-fa2--dist-3d vx vy vz))
               (speed-limit (truncate graph-fa2-speed-limit-threshold)))
          (if (> speed speed-limit)
              (progn
                (aset vel-x i (/ (* vx speed-limit) (+ speed speed-limit)))
                (aset vel-y i (/ (* vy speed-limit) (+ speed speed-limit)))
                (aset vel-z i (/ (* vz speed-limit) (+ speed speed-limit))))
            (aset vel-x i vx)
            (aset vel-y i vy)
            (aset vel-z i vz)))
        (let* ((vx-disp (graph-fa2-clamp (ash (aref vel-x i) -4) graph-fa2-max-velocity))
               (vy-disp (graph-fa2-clamp (ash (aref vel-y i) -4) graph-fa2-max-velocity))
               (vz-disp (graph-fa2-clamp (ash (aref vel-z i) -4) graph-fa2-max-velocity)))
          (aset pos-x i (+ nx vx-disp))
          (aset pos-y i (+ ny vy-disp))
          (aset pos-z i (+ nz vz-disp)))
        (let* ((horizon (truncate graph-fa2-horizon-threshold))
               (horizon-start (truncate graph-fa2-horizon-start-threshold))
               (new-nx (aref pos-x i))
               (new-ny (aref pos-y i))
               (new-nz (aref pos-z i))
               (new-dist (graph-fa2--dist-3d new-nx new-ny new-nz))
               (scaled-radius (ash (truncate graph-fa2-surface-radius) 8))
               (target-dist new-dist))
          (cond
           ((eq graph-fa2-surface-constraint 'strict)
            (setq target-dist scaled-radius))
           ((eq graph-fa2-surface-constraint 'floor)
            (when (< new-dist scaled-radius)
              (setq target-dist scaled-radius)))
           ((eq graph-fa2-surface-constraint 'ceiling)
            (when (> new-dist scaled-radius)
              (setq target-dist scaled-radius)))
           ((eq graph-fa2-surface-constraint 'anneal)
            (let ((inv-progress (- 256 progress-fp)))
              (setq target-dist (ash (+ (* new-dist inv-progress) (* scaled-radius progress-fp)) -8)))))
          (when (and (> new-dist 0) (not (= target-dist new-dist)))
            (let ((clamp-scale (/ (ash target-dist 16) new-dist)))
              (aset pos-x i (ash (* new-nx clamp-scale) -16))
              (aset pos-y i (ash (* new-ny clamp-scale) -16))
              (aset pos-z i (ash (* new-nz clamp-scale) -16))
              (setq new-dist target-dist)))
          (when (= new-dist 0)
            (aset pos-x i target-dist)
            (setq new-dist target-dist))
          (when (> new-dist horizon)
            (let ((clamp-scale (/ (ash horizon 16) new-dist)))
              (aset pos-x i (ash (* (aref pos-x i) clamp-scale) -16))
              (aset pos-y i (ash (* (aref pos-y i) clamp-scale) -16))
              (aset pos-z i (ash (* (aref pos-z i) clamp-scale) -16))
              (setq new-dist horizon)))
          (cond
           ((>= new-dist horizon)
            (aset vel-x i 0)
            (aset vel-y i 0)
            (aset vel-z i 0))
           ((> new-dist horizon-start)
            (aset vel-x i (- (aref vel-x i) (ash (aref vel-x i) -2)))
            (aset vel-y i (- (aref vel-y i) (ash (aref vel-y i) -2)))
            (aset vel-z i (- (aref vel-z i) (ash (aref vel-z i) -2))))
           (t
            (aset vel-x i (- (aref vel-x i) (ash (aref vel-x i) -6)))
            (aset vel-y i (- (aref vel-y i) (ash (aref vel-y i) -6)))
            (aset vel-z i (- (aref vel-z i) (ash (aref vel-z i) -6))))))))))

(defun baseline-3d-physics-tick (ctx max-frames)
  "Calculate baseline ForceAtlas2 3D physics tick using pre-allocated arrays in CTX."
  (if (eq graph-fa2-engine '2d)
      (baseline-2d-physics-tick ctx max-frames)
    (let* ((nodes (graph-fa2-ctx-nodes ctx))
           (total-nodes (length nodes)))
      (if (= total-nodes 0)
          (graph-fa2--render-empty ctx)
        (let* ((bg-frame (graph-fa2-ctx-bg-frame ctx))
               (len (if (< bg-frame 100)
                        (max 1 (truncate (* total-nodes (/ (float (1+ bg-frame)) 100.0))))
                      total-nodes))
               (a (max 2 (truncate (* 256.0 (- 1.0 (/ (float bg-frame) max-frames))))))
               (progress-fp (min 256 (max 0 (truncate (* 256.0 (/ (float bg-frame) max-frames)))))))
          (baseline-compute-repulsion-3d ctx len a)
          (let ((gc-cons-threshold most-positive-fixnum))
            (dotimes (_ graph-fa2-substeps)
              (baseline-apply-repulsion-3d ctx len)
              (baseline-apply-attraction-3d ctx len a)
              (baseline-integrate-and-cull-3d ctx len a progress-fp)))
          (baseline-sync-nodes ctx total-nodes)
          (baseline-render-svg ctx len))))))

(defun baseline-render-chunk-cooperative (ctx cache-file hash-file target-hash target-buf max-frames playback-fps)
  "Render a simulation chunk cooperatively using baseline implementation."
  (cl-symbol-macrolet ((frames-rendered (graph-fa2-ctx-frames-rendered ctx))
                       (playback-started (graph-fa2-ctx-playback-started ctx))
                       (bg-buffer (graph-fa2-ctx-bg-buffer ctx))
                       (heavy-frames (graph-fa2-ctx-heavy-frames ctx))
                       (heavy-time (graph-fa2-ctx-heavy-time ctx))
                       (bg-frame (graph-fa2-ctx-bg-frame ctx))
                       (bg-timer (graph-fa2-ctx-bg-timer ctx)))
    (let* ((chunk-end-time (time-add nil 0.05))
           (slice-start-time (float-time))
           (slice-start-frames frames-rendered)
           (frames-in-slice 0)
           (playback-ms (/ 1.0 playback-fps))
           (gc-cons-threshold most-positive-fixnum))
      (while (and (< frames-rendered max-frames)
                  (time-less-p nil chunk-end-time)
                  (not (input-pending-p)))
        (setf bg-frame frames-rendered)
        (baseline-3d-physics-tick ctx max-frames)
        (setf frames-rendered (1+ frames-rendered))
        (cl-incf frames-in-slice))
      (let* ((slice-duration (* (- (float-time) slice-start-time) 1000.0))
             (valid-frames (max 0 (- frames-rendered (max 100 slice-start-frames)))))
        (when-let* ((has-valid-frames (> valid-frames 0)))
          (setf heavy-frames (+ heavy-frames valid-frames))
          (setf heavy-time (+ heavy-time (* slice-duration (/ (float valid-frames) frames-in-slice)))))
        (let ((cumulative-avg (if (> heavy-frames 0)
                                  (/ heavy-time heavy-frames)
                                0.0)))
          (unless (or playback-started
                      (< frames-rendered 100)
                      (= heavy-frames 0))
            (let* ((tg (/ cumulative-avg 1000.0))
                   (predicted-tg (+ tg 0.020))
                   (safe-buffer
                    (if (<= predicted-tg playback-ms)
                        1
                      (ceiling (* max-frames (/ (- predicted-tg playback-ms) predicted-tg))))))
              (when-let* ((buffer-ready (>= frames-rendered (+ 100 safe-buffer))))
                (setf playback-started t)
                (when-let* ((has-cache cache-file))
                  (with-current-buffer bg-buffer
                    (let ((coding-system-for-write 'utf-8))
                      (write-region (point-min) (point-max) cache-file nil 'silent))))
                (when-let* ((is-live (buffer-live-p target-buf)))
                  (if-let* ((has-cache cache-file))
                      (graph-fa2--load-playback-from-cache ctx cache-file target-buf)
                    (graph-fa2-player-start))))))
          (when-let* ((can-reload (and playback-started (< frames-rendered max-frames))))
            (graph-fa2--hot-reload-player target-buf bg-buffer)))
        (if-let* ((continue-sim (< frames-rendered max-frames)))
            (setf bg-timer
                  (run-at-time 0 nil #'baseline-render-chunk ctx cache-file hash-file target-hash target-buf max-frames playback-fps))
          (when-let* ((has-cache cache-file))
            (with-current-buffer bg-buffer
              (let ((coding-system-for-write 'utf-8))
                (write-region (point-min) (point-max) cache-file nil 'silent))))
          (when-let* ((has-hash hash-file))
            (with-temp-file hash-file (insert target-hash)))
          (when-let* ((need-render (and (buffer-live-p target-buf) (not playback-started))))
            (when-let* ((has-cache cache-file))
              (baseline-render-chunk ctx cache-file hash-file target-hash target-buf max-frames playback-fps))))))))

(defun baseline-render-chunk (ctx cache-file hash-file target-hash target-buf max-frames playback-fps)
  "Cooperatively render frames using baseline implementation."
  (let* ((cached-hash (when-let* ((has-hash (and hash-file (file-exists-p hash-file))))
                        (with-temp-buffer
                          (let ((coding-system-for-read 'utf-8))
                            (insert-file-contents hash-file))
                          (string-trim (buffer-string)))))
         (has-valid-cache (and cached-hash
                               target-hash
                               (string= target-hash cached-hash)
                               cache-file
                               (file-exists-p cache-file))))
    (if-let* ((valid has-valid-cache))
        (when-let* ((num-frames (graph-fa2--load-playback-from-cache ctx cache-file target-buf)))
          (setq max-frames num-frames)
          (setf (graph-fa2-ctx-frames-rendered ctx) max-frames)
          (setf (graph-fa2-ctx-playback-started ctx) t))
      (baseline-render-chunk-cooperative ctx cache-file hash-file target-hash target-buf max-frames playback-fps))))

(provide 'graph-fa2-baseline)
;;; graph-fa2-baseline.el ends here
